# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sls < Formula
  desc "A smart fuzzy CLI selector for SSH config hosts"
  homepage "https://github.com/jinmugo/sls"
  version "0.1.0"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jinmugo/sls/releases/download/0.1.0/sls_Darwin_x86_64.tar.gz"
      sha256 "f10c648288c2196a1069aef780cf4fd53fc19184054783dff1f11990d036ede2"

      def install
        bin.install "sls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jinmugo/sls/releases/download/0.1.0/sls_Darwin_arm64.tar.gz"
      sha256 "ebab0e69c52f78683dce1c101eca3f682879a09f4da6be4a34616c0b8e32b672"

      def install
        bin.install "sls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jinmugo/sls/releases/download/0.1.0/sls_Linux_x86_64.tar.gz"
      sha256 "c5532e3802b8abbf600a62c39631c04f258ded122db01c38a1b256b7f720229c"
      def install
        bin.install "sls"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jinmugo/sls/releases/download/0.1.0/sls_Linux_arm64.tar.gz"
      sha256 "f39ffe461b18e723dbd917d227d2ed202dd7979d4a832caf011fef515177e307"
      def install
        bin.install "sls"
      end
    end
  end

  test do
    system "#{bin}/sls version"
  end
end
